//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employees : Persons, IRol
{
	public virtual void DevelopUnitTest()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DevelopDeployment()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DevelopProgramm()
	{
		throw new System.NotImplementedException();
	}

	public virtual void LogIn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateBillingTemplate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateSalaryTemplate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AttendToMeetings()
	{
		throw new System.NotImplementedException();
	}

}

