//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IRol 
{
	object SkillAsDeveloper { get;set; }

	object SkillAsAccountant { get;set; }

	void DevelopUnitTest();

	void DevelopDeployment();

	void DevelopProgramm();

	void CreateBillingTemplate();

	void CreateSalaryTemplate();

	void AttendToMeetings();

}

