//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OfficeBillingProcess
{
	public virtual Employees Employee
	{
		get;
		set;
	}

	public virtual void PayLoans()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PaySalaryEmployees(Employees eployee)
	{
		throw new System.NotImplementedException();
	}

	public virtual void HireEmployee(Prototype employee)
	{
		throw new System.NotImplementedException();
	}

}

