//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Persons
{
	public virtual int IdNumber
	{
		get;
		set;
	}

	public virtual string SSN
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string MiddleName
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

}

